test: &test
  filters:
    tags:
      ignore: /.*/
    branches:
      only: /.*/


version: 2.1
jobs:
  deployment-checks: 
    macos:
      xcode: "12.3.0"
    working_directory: ~/revenuex-ios-sdk
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout

      # Bundler
      - restore_cache:
          keys: 
            - gem-cache-{{ checksum "Gemfile.lock" }}
      - run: bundle install --clean --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      
      # - run:
      #     name: Deployment checks
      #     command: bundle exec fastlane deployment_checks
      #     environment:
      #       SCAN_SCHEME: All Tests
      # - store_test_results:
      #     path: fastlane/test_output
      # - store_artifacts:
      #     path: fastlane/test_output/report.html
      #     destination: test_report.html 

workflows:
  version: 2
  build-test:
    jobs:
      # - runtest
      - deployment-checks: *test