release-branches: &release-branches
  filters:
    tags:
      ignore: /.*/
    branches:
      only: /^release\/.*/

release-tags: &release-tags
  filters: 
    tags:
      ignore: /^.*-COPY/
    branches:
      ignore: /.*/


version: 2.1
commands:
  install-gems:
    parameters:
      directory:
        type: string
        default: .
    steps:
       # Bundler
      - restore_cache:
          keys: 
            - gem-cache-{{ checksum "Gemfile.lock" }}
      - run: 
          name: Bundle install
          working_directory: << parameters.directory >>
          command: bundle install --clean --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle


jobs:
  deployment-checks: 
    macos:
      xcode: "12.2.0"
    working_directory: ~/revenuex-ios-sdk
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout

      - restore_cache:
          keys: 
            - gem-cache-{{ checksum "Gemfile.lock" }}
      - run: bundle install --clean --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      
      - run:
          name: Deployment checks
          command: bundle exec fastlane check_before_deploy

          
  
  release:
    macos:
      xcode: "12.2.0"
    working_directory: ~/revenuex-ios-sdk/
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - install-gems
      - run:
          name: Deploy new version
          command: bundle exec fastlane deploy

  prepare-next:
    macos:
      xcode: "12.2.0"
    working_directory: ~/revenuex-ios-sdk/
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - install-gems
      - run:
          name: Prepare next version
          command: bundle exec fastlane prepare_next

workflows:
  version: 2
  build-test:
    jobs:
      - deployment-checks: *release-branches
    
  deploy:
    jobs:
      - release: *release-tags
      - prepare-next: *release-tags
