# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Increment build number"
  lane :bump do |options|
    new_version_number = options[:version]
    fail ArgumentError, "missing version" unless new_version_number
    previous_version_number =  get_version_number(target: "Revenuex")
    increment_version_number(version_number: new_version_number)
    files_to_update = [
      '../RevenueX.podspec',
    ]
    for file_to_update in files_to_update
      increment_build_number(previous_version_number, new_version_number, file_to_update)
    end
  end

  desc "Deployment checks"
  lane :deployment_checks do |options|
    version_number = get_version_number(target: "Revenuex")
    check_no_git_tag_exists(version_number)
    check_pods
    carthage_archive
    export_xcframework
    check_no_github_release_exists(version_number)
  end


  desc "Deploy"
  lane :deploy do |options|
    version_number = get_version_number(target: "Revenuex")
    # pod_push(path: "RevenueX.podspec")
    export_xcframework
    github_release(version: version_number)
  end

  desc "Prepare next version"
  lane :prepare_next_version do |options|
    current_version_number = get_version_number(target: "Revenuex")
    major, minor, _ = current_version_number.split('.')
    next_version = "#{major}.#{minor.to_i + 1}.0"
    next_version_snapshot = "#{next_version}-SNAPSHOT"

    branch_name = "bump/#{next_version_snapshot}"
    sh("git", "checkout", "-b", branch_name)

    bump(version: next_version_snapshot)

    sh("git", "commit", "-am", "Preparing for next version")
    push_to_git_remote

    create_pull_request(
      repo: "revenue-plus/revenuex-ios-sdk",
      title: "Prepare next version: #{next_version_snapshot}",
      base: "develop",
      api_token: "054388ce5cf443a6891981ef4a49706b390d6ef9"
    )
  end


  desc "Make github release"
  lane :github_release do |options|
    release_version = options[:version]
    fail ArgumentError, "missing version" unless release_version

    begin
      changelog = File.read("../CHANGELOG.latest.md")
    rescue
      fail "please add a CHANGELOG.latest.md file before calling this lane"
    end

    set_github_release(
      repository_name: "revenue-plus/revenuex-ios-sdk",
      # api_token: ENV["GITHUB_TOKEN"],
      api_token: "054388ce5cf443a6891981ef4a49706b390d6ef9",
      name: release_version,
      tag_name: "#{release_version}",
      description: changelog,
      commitish: "develop",
      upload_assets: ["Revenuex.xcframework.zip"],
      is_draft: false
  )
  end

  desc "Export XCFramework"
  lane :export_xcframework do |options|
    output_directory = 'build/xcframeworks'
    platforms = [
        'iOS'
      ]

    create_xcframework(
      destinations: platforms,
      scheme: 'Revenuex',
      xcframework_output_directory: output_directory,
      enable_bitcode: false
    )
    # sh runs from the Fastfile's location, but other commands run from the project root.
    output_directory_for_sh = "../#{output_directory}"

    xcframeworks_zip_path_for_sh = "../Revenuex.xcframework.zip"
    sh("ditto", "-c", "-k", "--sequesterRsrc", "--keepParent", 
      output_directory_for_sh, 
      xcframeworks_zip_path_for_sh)

  end

  desc "Increment build number and update changelog"
  lane :bump_and_update_changelog do |options|
    bump(options)
    attach_changelog_to_master(options[:version])
  end

end

def increment_build_number(previous_version_number, new_version_number, file_path)
  sed_regex = 's|' + previous_version_number + '|' + new_version_number + '|'
  backup_extension = '.bck'
  sh("sed", '-i', backup_extension, sed_regex, file_path)
end

def attach_changelog_to_master(version_number)
  current_changelog = File.open("../CHANGELOG.latest.md", 'r')
  master_changelog = File.open("../CHANGELOG.md", 'r')

  current_changelog_data = current_changelog.read
  master_changelog_data = master_changelog.read

  current_changelog.close  
  master_changelog.close

  File.open("../CHANGELOG.md", 'w') { |master_changelog_write_mode|
    version_header = "## #{version_number}"
    whole_file_data = "#{version_header}\n#{current_changelog_data}\n#{master_changelog_data}"
    puts "going to save. Contents - #{whole_file_data}"
    
    master_changelog_write_mode.write(whole_file_data)
  }
end

def check_no_git_tag_exists(version_number)
  if git_tag_exists(tag: version_number, remote: true, remote_name: 'origin')
    raise "git tag with version #{version_number} already exists!"
  end
end


